# Generated by Django 2.2 on 2021-03-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmng', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='created_by',
            new_name='sec_fillings',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='issue_by',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='issue_to',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='export_to_csv',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='issue_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='receive_quantity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_yield',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='earnings_share',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ebitda',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fifty_two_week_high',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='fifty_two_week_low',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_book',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_earnings',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_sales',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
